- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600  

- name: "{{ 'Remove' if state == 'absent' else 'Setup' }} Dotnet"
  become: yes
  apt:
    name: dotnet-sdk-8.0
    state: "{{ state }}"