---
- name: Install GitHub CLI (gh)
  apt:
    deb: https://github.com/cli/cli/releases/download/v2.49.0/gh_2.49.0_linux_amd64.deb
    state: present
  when: state == "present"

- name: Uninstall GitHub CLI (gh)
  apt:
    name: gh
    state: absent
  when: state == "absent"