---
- name: Setup Dev Environment
  hosts: localhost
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install essential packages
      apt:
        name:
          - curl
          - git
        state: present

    - name: Install GitHub CLI (gh)
      apt:
        deb: https://github.com/cli/cli/releases/download/v2.49.0/gh_2.49.0_linux_amd64.deb

    - name: Install Devbox
      shell: |
        curl -fsSL https://get.jetpack.io/devbox | bash
      args:
        creates: /usr/local/bin/devbox

    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VS Code repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present
        filename: vscode

    - name: Install Visual Studio Code
      apt:
        name: code
        state: present
