---
- name: Install Deps and Tools
  hosts: "{{ target_hosts | default('localhost') }}"
  become: true

  tasks:
    - name: Show which host this is running on
      debug:
        msg: "Running on {{ inventory_hostname }}"

    - name: Include dependencies
      include_tasks:
      file: tasks/install_deps.yml
      apply:
        tags: deps

    - name: Include Devbox installation
      include_tasks:
      file: tasks/install_devbox.yml
      apply:
        tags: devbox

    - name: Include Git Hub CLI installation
      include_tasks:
      file: tasks/install_github_cli.yml
      apply:
        tags: githubcli

    - name: Include VSCode installation
      include_tasks:
      file: tasks/install_vscode.yml
      apply:
        tags: vscode
