---
- name: Running Ansible Roles
  hosts: "{{ target_hosts | default('localhost') }}"  
  roles:
    - role: deps
      tags: deps

    - role: devbox
      tags: devbox

    - role: githubcli
      tags: githubcli    
    
    - role: vscode
      tags: vscode  

    - role: docker
      tags: docker   
    
    - role: vagrant
      tags: vagrant  

    - role: packer
      tags: packer
      
    - role: virtualbox
      tags: virtualbox
 
    - role: zsh
      tags: zsh
    
    - role: dotnet
      tags: dotnet

    - role: python
      tags: python
    
    - role: ruby
      tags: ruby

    - role: hcp
      tags: hcp

    - role: rider
      tags: rider

    - role: microk8s
      tags: microk8s