---
- name: Running Ansible Roles
  hosts: "{{ target_hosts | default('localhost') }}"  
  roles:
    - role: deps
      tags: deps

    - role: zsh
      tags: zsh

    - role: devbox
      tags: devbox

    - role: githubcli
      tags: githubcli    
    
    - role: vscode
      tags: vscode  

    - role: docker
      tags: docker   
    
    - role: vagrant
      tags: vagrant  

    - role: packer
      tags: packer
      
    - role: virtualbox
      tags: virtualbox