---
- name: Setup Dev Environment
  hosts: localhost
  become: yes
  vars:
    state: present # Can be overridden with --extra-vars state=absent

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install essential packages
      apt:
        name:
          - curl
          - git
        state: "{{ state }}"

    - name: Install GitHub CLI (gh)
      apt:
        deb: https://github.com/cli/cli/releases/download/v2.49.0/gh_2.49.0_linux_amd64.deb

    - name: Install Devbox via official script
      shell: |
        curl -fsSL https://get.jetpack.io/devbox | bash -s -- --force
      args:
        executable: /bin/bash
        creates: /usr/local/bin/devbox
      when: state == "present"

    - name: Install or Uninstall Devbox binary
      file:
        path: /usr/local/bin/devbox
        state: "{{ state }}"
      when: state == "absent"

    - name: Manage Devbox bash completion
      file:
        path: /etc/bash_completion.d/devbox
        state: "{{ state }}"
      when: state == "absent"

    - name: Manage Devbox user config
      file:
        path: "{{ ansible_env.HOME }}/.devbox"
        state: "{{ state }}"
      when: state == "absent"

    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: "{{ state }}"

    - name: Add VS Code repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: "{{ state }}"
        filename: vscode

    - name: Install Visual Studio Code
      apt:
        name: code
        state: "{{ state }}"
