# -*- mode: ruby -*-
# vi: set ft=ruby :

# Import the base box from ../ubuntu-autoinstall/vagrant-base/Vagrantfile.base
File.expand_path("../ubuntu-autoinstall/vagrant-base/Vagrantfile.base", __FILE__)  

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-dev"
  # Run bootstrap script on first boot
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    echo "Downloading and running bootstrap..."
    wget --header="Cache-Control: no-cache" -qO- "https://raw.githubusercontent.com/arslan-qamar/devsetups/refs/heads/main/bootstrap.sh?ts=$(date +%s)" | bash -s "main.yml" "localhost," "local" "present" "deps,devbox,docker,githubcli,vscode"
  SHELL
end
