# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_CUSTOM_KEY_PATH'] ||= '../ubuntu-autoinstall/vagrant_custom_key'
# Resolve the custom key path on the host and define a temporary path in the VM
ssh_key_tmp = "/tmp/id_ed25519"
ssh_key_pub_tmp = "/tmp/id_ed25519.pub"

ssh_key_dest = "~/.ssh/id_ed25519"
ssh_key_pub_dest = "~/.ssh/id_ed25519.pub"

hcp_creds_tmp = "/tmp/cred_file.json"
hcp_creds_folder = "~/.config/hcp/credentials"
hcp_creds_dest = "~/.config/hcp/credentials/cred_file.json"


# Load the base Vagrantfile
load File.expand_path("../ubuntu-autoinstall/vagrant-base/Vagrantfile.base", __dir__)

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-dev" 

  # Copy the custom SSH key from host to a temporary location in the VM
  config.vm.provision "file", source: ssh_key_dest, destination: ssh_key_tmp  
  config.vm.provision "file", source: ssh_key_pub_dest, destination: ssh_key_pub_tmp  
  config.vm.provision "file", source: hcp_creds_dest, destination: hcp_creds_tmp
  
  # Run bootstrap script on first boot
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    set -e
    echo "Downloading and running bootstrap..."
    # wget --header="Cache-Control: no-cache" -qO- "https://raw.githubusercontent.com/arslan-qamar/devsetups/refs/heads/main/bootstrap.sh?ts=$(date +%s)" | bash -s "main.yml" "localhost," "local" "install" "python,deps,devbox,docker,githubcli,vscode,zsh,dotnet,hcp,rider"      
    
    # Move the custom keys to ~/.ssh and set permissions
    echo "Setting up Host SSH key for git clone..."
    
    if [ ! -f "#{ssh_key_dest}" ]; then
      echo "Copying Host SSH key for git clone..."    
      mv #{ssh_key_tmp} #{ssh_key_dest}
      mv #{ssh_key_pub_tmp} #{ssh_key_pub_dest}
    else
      echo "SSH key file already found at ~/.ssh/id_ed25519, skipping SSH key setup."
    fi    

    if [ ! -f "#{hcp_creds_dest}" ]; then
      echo "Copying Hcp creds for vault access..."    
      mkdir -p #{hcp_creds_folder}
      mv #{hcp_creds_tmp} #{hcp_creds_dest}
    else
      echo "No Hcp vault creds found. .envrc file wont be setup !!!"
    fi 
    
    if [ ! -d "interactivebrokers2" ]; then
      GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@github.com:arslan-qamar/interactivebrokers2.git
      cd interactivebrokers2
      echo 'export IBKR_DB_PAPER='$(hcp vault-secrets secrets open ibkr_db_paper --app Bot | sed -n 's/^Value: *//p') >> .envrc
      echo 'export IBKR_DB_LIVE='$(hcp vault-secrets secrets open ibkr_db_live --app Bot | sed -n 's/^Value: *//p') >> .envrc
      echo 'export TEST_ACCOUNT='$(hcp vault-secrets secrets open test_account --app Bot | sed -n 's/^Value: *//p') >> .envrc
    fi
    
    git config --global commit.gpgsign true
    git config --global tag.gpgSign true
    git config --global gpg.format ssh
    git config --global user.signingkey #{ssh_key_pub_dest}      
    
    wget https://download2.interactivebrokers.com/installers/tws/latest-standalone/tws-latest-standalone-linux-x64.sh && chmod +x tws-latest-standalone-linux-x64.sh && ./tws-latest-standalone-linux-x64.sh -q

    
  SHELL
  
  # Add VirtualBox-specific customizations
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "16384"    
  end
  
end
