---
- name: Ensure Devbox is installed or removed
  become: true
  vars:
    devbox_path: /usr/local/bin/devbox

  tasks:
    - name: Install Devbox
      shell: curl -fsSL https://get.jetpack.io/devbox | bash -s -- --force
      args:
        creates: "{{ devbox_path }}"
      when: state == 'present'

    - name: Remove Devbox
      file:
        path: "{{ devbox_path }}"
        state: absent
      when: state == 'absent'