---
- name: Install Devbox via official script
  shell: |
    curl -fsSL https://get.jetify.com/devbox | bash -s -- --force
  args:
    executable: /bin/bash
    creates: /usr/local/bin/devbox
  when: state == "present"

- name: Make Devbox executable by everyone
  file:
    path: /usr/local/bin/devbox
    mode: '0755'
    owner: root
    group: root
    state: file
  when: state == "present"

- name: Install or Uninstall Devbox binary
  file:
    path: /usr/local/bin/devbox
    state: "{{ state }}"
  when: state == "absent"

- name: Manage Devbox bash completion
  file:
    path: /etc/bash_completion.d/devbox
    state: "{{ state }}"
  when: state == "absent"

- name: Manage Devbox user config
  file:
    path: "{{ ansible_env.HOME }}/.devbox"
    state: "{{ state }}"
  when: state == "absent"