---
- name: Add Microsoft GPG key
  become: true
  apt_key:  
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: "{{ state }}"

- name: Add VS Code repository
  become: true
  apt_repository:  
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: "{{ state }}"
    filename: vscode

- name: Install Visual Studio Code
  become: true
  apt:
    name: code
    state: "{{ state }}"

- name: Install VS Code extensions  
  tasks:
    - name: Ensure VS Code extensions are installed
      become: yes
      become_user: "{{ ansible_user }}"
      shell: |
        code --install-extension GitHub.copilot
        code --install-extension ms-python.python
        code --install-extension esbenp.prettier-vscode
        code --install-extension ms-dotnettools.csdevkit
        code --install-extension ms-dotnettools.csharp
        code --install-extension VisualStudioExptTeam.vscodeintellicode-csharp      