---
- name: Add Microsoft GPG key
  apt_key:
  become: true
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: "{{ state }}"

- name: Add VS Code repository
  apt_repository:
  become: true
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: "{{ state }}"
    filename: vscode

- name: Install Visual Studio Code
  apt:
    name: code
    state: "{{ state }}"
