---
- name: Add Microsoft GPG key
  become: true
  apt_key:  
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: "{{ state }}"

- name: Add VS Code repository
  become: true
  apt_repository:  
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: "{{ state }}"
    filename: vscode

- name: Install Visual Studio Code
  become: true
  apt:
    name: code
    state: "{{ state }}"

- name: Ensure VS Code extensions are installed
  become: false
  become_user: "{{ ansible_env.USER }}"
  shell: |
    code --install-extension GitHub.copilot --no-sandbox --user-data-dir /home/{{ ansible_env.USER }}/.config/Code
    code --install-extension ms-python.python --no-sandbox --user-data-dir /home/{{ ansible_env.USER }}/.config/Code
    code --install-extension esbenp.prettier-vscode --no-sandbox --user-data-dir /home/{{ ansible_env.USER }}/.config/Code
    code --install-extension ms-dotnettools.csdevkit --no-sandbox --user-data-dir /home/{{ ansible_env.USER }}/.config/Code
    code --install-extension ms-dotnettools.csharp --no-sandbox --user-data-dir /home/{{ ansible_env.USER }}/.config/Code