---
- name: Install VirtualBox and Vagrant on Ubuntu
  hosts: localhost
  become: true
  tasks:

    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies
      apt:
        name:
          - curl
          - gnupg2
          - software-properties-common
        state: present

    - name: Add VirtualBox apt repository key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add VirtualBox repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian jammy contrib'
        state: present
        filename: virtualbox

    - name: Install VirtualBox
      apt:
        name: virtualbox-7.0
        state: present
        update_cache: yes

    - name: Download Vagrant deb package
      get_url:
        url: https://releases.hashicorp.com/vagrant/2.4.1/vagrant_2.4.1-1_amd64.deb
        dest: /tmp/vagrant.deb

    - name: Install Vagrant
      apt:
        deb: /tmp/vagrant.deb
