---
- name: Ensure required packages are installed
  become: yes
  apt:
    name: 
      - wget
      - gpg
      - coreutils
    state: "{{ state }}"
    update_cache: yes

- name: Ensure /usr/share/keyrings directory exists
  become: yes
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  when: state == "present"

- name: Download and dearmor HashiCorp GPG key
  become: yes
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  when: state == "present"

- name: Remove HashiCorp GPG key
  become: yes
  file:
    path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    state: absent
  when: state == "absent"

- name: Manage HashiCorp apt repository
  become: yes
  apt_repository:
    repo: "deb [arch={{ ansible_architecture | default('amd64') }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    filename: hashicorp
    state: "{{ state }}"

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "{{ 'Remove' if state == 'absent' else 'Install' }} HCP CLI"
  become: yes
  apt:
    name: hcp
    state: "{{ state }}"

- name: "{{ 'Remove' if state == 'absent' else 'Install' }} HashiCorp Vault"
  become: yes
  apt:
    name: vault
    state: "{{ state }}"