- name: Manage HashiCorp GPG key 
  shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/hashicorp.gpg
  args:
    creates: /etc/apt/trusted.gpg.d/hashicorp.gpg
  become: yes
  when: state == "present"

- name: Remove HashiCorp GPG key
  file:
    path: /etc/apt/trusted.gpg.d/hashicorp.gpg
    state: absent
  become: yes
  when: state == "absent"

- name: Manage HashiCorp apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: "{{ state }}"
    filename: hashicorp

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600  

- name: "{{ 'Remove' if state == 'absent' else 'Setup' }} Packer"
  become: yes
  apt:
    name: packer
    state: "{{ state }}"

