- name: Ensure snapd is installed
  package:
    name: snapd
    state: present
  become: true

- name: Install microk8s
  community.general.snap:
    name: microk8s
    state: "{{ state }}"
    classic: true
  become: true
  when: state == 'present'

- name: Remove microk8s
  community.general.snap:
    name: microk8s
    state: absent
  become: true
  when: state == 'absent'

- name: Ensure user is in microk8s group
  user:
    name: "{{ ansible_user_id }}"
    groups: microk8s
    append: yes
  become: true
  when: state == 'present'

- name: Remove user from microk8s group
  user:
    name: "{{ ansible_user_id }}"
    groups: ""
    append: no
    remove: yes
  become: true
  when: state == 'absent'

- name: Set list of microk8s services
  set_fact:
    microk8s_services:
      - dns
      - storage
      - ingress
      - registry
      - dashboard

- name: Enable microk8s services one by one
  command: microk8s enable {{ item }}
  loop: "{{ microk8s_services }}"
  become: true
  when: state == 'present'
  changed_when: false

- name: Disable microk8s services one by one
  command: microk8s disable {{ item }}
  loop: "{{ microk8s_services }}"
  become: true
  when: state == 'absent'
  changed_when: false

- name: Ensure ~/.kube directory exists
  file:
    path: "/home/{{ ansible_user_id }}/.kube"
    state: directory
    mode: '0700'
  become: true
  when: state == 'present'

- name: Copy microk8s kubeconfig to ~/.kube/config
  copy:
    src: /var/snap/microk8s/current/credentials/client.config
    dest: "/home/{{ ansible_user_id }}/.kube/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0600'
    remote_src: yes
  become: true
  when: state == 'present'

- name: Remove kubeconfig from ~/.kube/config
  file:
    path: "/home/{{ ansible_user_id }}/.kube/config"
    state: absent
  become: true
  when: state == 'absent'