- name: "{{ 'Remove' if state == 'absent' else 'Install' }} libvirt packages"
  apt:
    name:
      - libvirt-daemon-system
      - libvirt-clients
      - libvirt-dev
      - virtinst
      - bridge-utils
      - dnsmasq-base
      - pkg-config
    state: "{{ state }}"
    update_cache: yes
  become: yes

- name: Ensure libvirtd service is enabled
  systemd:
    name: libvirtd
    enabled: yes
    state: started
  become: yes
  when: state == 'present'

- name: Ensure current user is in libvirt group
  user:
    name: "{{ ansible_user_id }}"
    groups: libvirt
    append: yes
  become: yes
  when: state == 'present'
