# Update apt package index and install required packages
- name: Update apt package index
  apt:
    update_cache: yes
  become: true
  when: state == 'present'

# Uninstall kubectl and remove Kubernetes apt repository (when desired)
- name: Uninstall kubectl
  apt:
    name: kubectl
    state: absent
    purge: yes
    update_cache: yes
  become: true
  when: state == 'absent'

- name: Remove Kubernetes apt repository
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent
  become: true
  when: state == 'absent'

- name: Remove Kubernetes apt keyring
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent
  become: true
  when: state == 'absent'

- name: Update apt package index (after uninstall)
  apt:
    update_cache: yes
  become: true
  when: state == 'absent'

- name: Install required packages for Kubernetes apt repository
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  become: true
  when: state == 'present'

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  when: state == 'present'

- name: Download Kubernetes apt signing key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true
  when: state == 'present'

- name: Set permissions on Kubernetes apt keyring
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
  become: true
  when: state == 'present'

- name: Add Kubernetes apt repository
  shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' > /etc/apt/sources.list.d/kubernetes.list
  args:
    creates: /etc/apt/sources.list.d/kubernetes.list
  become: true
  when: state == 'present'

- name: Set permissions on Kubernetes apt sources list
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'
  become: true
  when: state == 'present'

- name: Update apt package index (after adding repo)
  apt:
    update_cache: yes
  become: true
  when: state == 'present'

- name: Install kubectl
  apt:
    name: kubectl
    state: present
    update_cache: yes
  become: true
  when: state == 'present'
