---
- name: Update apt cache
  become: true
  apt:
    update_cache: yes  

- name: Install required dependencies
  become: true
  apt:
    name:
      - software-properties-common
    state: "{{ state }}"
  
- name: Add VirtualBox repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release | lower }} contrib"
    state: "{{ state }}"
    filename: "virtualbox"
  when: state == 'present'

- name: Add Oracle VirtualBox public key
  become: true
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: "{{ state }}"

- name: Install VirtualBox {{ virtualbox_version }}
  become: true
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: "{{ state }}"
