- name: "{{ 'Remove' if state == 'absent' else 'Add' }} Oracle VirtualBox repository key"
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: "{{ state }}"
  become: yes

- name: "{{ 'Remove' if state == 'absent' else 'Add' }} VirtualBox APT repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    state: "{{ state }}"
  become: yes

- name: "{{ 'Uninstall' if state == 'absent' else 'Install' }} VirtualBox"
  apt:
    name: virtualbox
    state: "{{ state }}"
  become: yes
