# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-dev"
  config.ssh.username = "ubuntu"
  config.ssh.password = "ubuntu" 
  config.ssh.insert_key = false
  default_interface = `ip route get 8.8.8.8 | grep -oP 'dev \\K\\S+'`.strip
  config.vm.network "public_network", bridge: default_interface
  config.vbguest.auto_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
  end
end
