# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-dev"
  config.ssh.username = "ubuntu"  
  config.ssh.private_key_path = ["~/.ssh/vagrant_custom_key"] 
  config.ssh.insert_key = false
  default_interface = `ip route get 8.8.8.8 | grep -oP 'dev \\K\\S+'`.strip
  config.vm.network "public_network", bridge: default_interface
  config.vbguest.auto_update = true

  # Run bootstrap script on first boot
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    echo "Downloading and running bootstrap..."
    wget --header="Cache-Control: no-cache" -qO- "https://raw.githubusercontent.com/arslan-qamar/devsetups/refs/heads/main/bootstrap.sh?ts=$(date +%s)" | bash -x -s "main.yml" "localhost," "local" "present" "deps,devbox,docker,githubcli,vscode"
  SHELL

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "8192"
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    vb.customize ["modifyvm", :id, "--audio", "alsa"]
    vb.customize ["modifyvm", :id, "--audiocontroller", "ac97"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--audioout", "on"]
  end
end
