---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: "{{ state }}"

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: "{{ state }}"

- name: Set up the Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: "{{ state }}"

- name: Update apt package index after adding Docker repo
  apt:
    update_cache: yes
  

- name: Install Docker CE
  apt:
    name: docker-ce
    state: "{{ state }}"
  when: state == "present"
  
  
- name: Gather service facts
  service_facts:

- name: Ensure Docker service is started
  assert:
    that:
      - "'docker.service' in ansible_facts.services"
      - "ansible_facts.services['docker.service'].state == 'running'"
  when: state == "present"

- name: Ensure Docker service is started
  service:
    name: docker
    state: "started"
  when: state == "present"


- name: Ensure Docker service is stopped
  assert:
    that:
      - "'docker.service' in ansible_facts.services"
      - "ansible_facts.services['docker.service'].state == 'stopped'"
  when: state == "absent"

- name: Ensure Docker service is absent
  service:
    name: docker
    state: "stopped"
  when: state == "absent"
