
# filepath: /home/arslan/devsetups/roles/ruby/tasks/main.yml
---
- name: Ensure Ruby is installed
  apt:
    name: ruby
    state: "{{ state }}"
    update_cache: yes
  become: yes
  when: state == 'present'

- name: Ensure Bundler is configured
  gem:
    name: bundler
    state: "{{ state }}"
    user_install: yes

  when: state == 'present'
- name: Ensure Ruby is absent
  apt:
    name: ruby
    state: absent
    purge: yes
  become: yes
  when: state == 'absent'