name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Validate docker-compose file
      run: docker compose config
    
    - name: Run basic tests
      run: |
        echo "Running CI tests..."
        # Add your test commands here
        echo "CI tests completed successfully"